#!/bin/bash
docker run --name centos7 -d pycontribs/centos:7 sleep 6000000000
docker run --name ubuntu -d pycontribs/ubuntu sleep 6000000000 
docker run --name fedora -d pycontribs/fedora sleep 6000000000

ansible-playbook -i inventory/prod.yml site.yml --ask-vault-password

docker kill $(docker ps -q)